name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: wiikip/go-container:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Terraform init
        run: terraform init
        continue-on-error: true

      - name: Plan test
        run: terraform plan -no-color -var 'client_certificate=${{secrets.KUBE_CLIENT_CERTIFICATE}}' -var 'client_key=${{secrets.KUBE_CLIENT_KEY}}' -var 'ca-certificate=${{secrets.KUBE_CA_CERTIFICATE}}'
        continue-on-error: true
